/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBaseRewardPool } from "./IBaseRewardPool";
export type { IBooster } from "./IBooster";
export type { ICVX } from "./ICVX";
